apiVersion: v1
kind: Pod
metadata:
  name: server-pod-1
  labels:
    app.kubernetes.io/name: server
spec:
  containers:
  - image: nginx
    name: server-container-1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: server-pod-2
  labels:
    app.kubernetes.io/name: server
spec:
  containers:
  - image: nginx
    name: server-container-2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-client
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    name: client-container
    command:
    - tail
    - -f 
    - /dev/null
