apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - image: nginx
    name: container-1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - image: nginx
    name: container-2

