apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: MyApp
  name: my-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: MyApp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: MyApp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http-web-svc
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
