apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: MyApp
  name: my-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: MyApp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: MyApp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http-web-svc
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80 # This is port where service will listen
      targetPort: http-web-svc # This is a port on which container is listening
      nodePort: 30001 # This will be the port which will be exposed on the node for clients to connect
