apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen       81;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      # error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-pod
spec:
  restartPolicy: Never
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
  containers:
  - image: nginx
    name: container-1
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3

  - image: nginx
    name: container-2
    livenessProbe:
      httpGet:
        path: /notfound
        port: 81
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - containerPort: 81
    volumeMounts:
    - name: nginx-config
      readOnly: true
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf






