apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/env: dev
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/env: stag
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/env: prod
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app.kubernetes.io/name: myapp
    matchExpressions:
    - key: app.kubernetes.io/env
      operator: NotIn
      values:
      - dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376